feature 76 pcolormesh shading (difficulty index fix)
dtcenter/METplotpy pull request #77
Opened 2021-01-08 18:52 UTC by georgemccabe

Changed pcolormesh shading value to nearest because interp is not a valid choice. Updated expected image from pytest to an image that was created with matplotlib 3.3.3 using nearest. The new image does not have missing data at the edge (last row and column).

Notes copied from Slack conversation:

> 
> I looked into this a little more and it looks like shading='interp' was never a valid value for shading in plt.pcolormesh, so it would default to 'flat.' Before 3.3 it would silently remove the last row and column of the data (see https://matplotlib.org/3.3.3/gallery/images_contours_and_fields/pcolormesh_grids.html#flat-shading-same-shape-grid)
> I created images using each of the shading methods and they are all different from the expected image. The "flat" shading is the closest because it also cuts off some of the data, but running this way is deprecated and will completed fail in a future version. "nearest" and "auto"  produce the same output and it pretty much look like the expected image except they have the last row and column that was previously removed. "gouraud" produces images with weird Xs on the borders and looks the most different, although the pytest image diff says it is closed to 1 to 1 than the others.
> Here are the pytest results: (using latest matplotlib)
> nearest: assert 0.8460561481710492 == 1
> auto: assert 0.8460561481710492 == 1
> gouraud: assert 0.8972081876599515 == 1
> flat: assert 0.9922975010967231 == 1 (deprecated in 2 versions)

Current expected diff image:
![diff_index_expected](https://user-images.githubusercontent.com/23407799/104052960-b996fb00-51a7-11eb-9807-f6b80b09597b.png)

Output using shading='auto':
![swh_North_Pacific_difficulty_index_9_00_feet_auto](https://user-images.githubusercontent.com/23407799/104053010-cc113480-51a7-11eb-9e93-af32accdc9aa.png)

Output using shading='nearest':
![swh_North_Pacific_difficulty_index_9_00_feet_nearest](https://user-images.githubusercontent.com/23407799/104053078-e1865e80-51a7-11eb-86f6-77247c4a5c56.png)

Output using shading='gouraud':

![swh_North_Pacific_difficulty_index_9_00_feet_gouraud](https://user-images.githubusercontent.com/23407799/104053058-dc291400-51a7-11eb-88d4-737e27173dad.png)

Output using shading='flat' (deprecated):
![swh_North_Pacific_difficulty_index_9_00_feet_flat](https://user-images.githubusercontent.com/23407799/104053092-e814d600-51a7-11eb-923a-ca680229df24.png)

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>
Verified that output image looks the same as the old except the missing values are displayed. Confirmed that METplus use case (model_applications/medium_range/UserScript_METcalcpy_METplotpy_Difficulty_Index.conf) runs successfully and produces reasonable output using METcalcpy (develop), METplotpy (develop), matplotlib (latest - 3.3.3), and scipy packages.

- [X] Recommend testing for the reviewer to perform, including the location of input datasets:</br>
Review notes and output and decide if changes are reasonable.

- [X] Will this PR result in changes to the test suite? **[Yes]**</br>
Output data will change, but test should still pass.

- [X] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.

2021-01-15 22:31 UTC, lindsayrblank requested changes
The changes produce the correct image except for the title font which is causing the pytest to fail. I'm not sure why the font is different between the two. I'm running with matplotlib 3.3.2 for reference. 

The diff_expected_image needs to have the title font changed before these changes can be approved.

2021-01-19 16:50 UTC, georgemccabe commented
To help debug this, the conda environment I used on kiowa to generate the new test results is:

/home/met_test/.conda/envs/metcalcpy_test

2021-01-25 18:17 UTC, lindsayrblank commented
> /home/met_test/.conda/envs/metcalcpy_test

Using this conda environment fixed the issue and now the pytest passes. This can be merged into develop now.

2021-01-25 18:18 UTC, lindsayrblank approved these changes

2021-01-25 18:18 UTC, merged